### ISSUE TITLE
streams2

### ISSUE THREAD

**Issue by jonathanong** [slate/slate-irc-parser#1]
so you can pipe the messages (as objects) to clients. it would emit `data` events instead of `message`. otherwise you have to do silly `.on('message', function (msg) res.write(msg) })` stuff

**Comment by tj** [comment]
mehh, object mode is super weird

**Comment by joaoneto** [comment]
Enjoying this discussion, my question is: What about the `Stream.Transform` to parse, there is loss of performance? 
Thinking about using transformation, emits 'message' would be optional, a branch for processing in the client stream already emits 'data' after parse.

**Comment by simnalamburt** [comment]
I'd like to stick to the native stream of node.js instead of stream2. Native stream is fine and its ergonomic is even better if you use [stream/promises](https://nodejs.org/api/stream.html#streams-promises-api) api which has added at Node.js v15. And with native stream, you get less dependencies and less bundle size.
